project:
  title: "MLUno API Reference"
  type: website

# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml

website:
  title: "MLUno"
  
  navbar:
    left:
      - href: reference\index.qmd
        text: Reference
  
quartodoc:
  # the name used to import the package you want to create reference docs for
  title: "MLUno API Reference"
  package: mluno

  # write sidebar data to this file
  sidebar: _sidebar.yml

  sections:

    - title: Data Utilities
      desc: Functions for simulating and splitting data.
      package: mluno.data
      contents:
        - make_line_data
        - make_sine_data
        - split_data

    
    - title: Regressors
      desc: Functions for simulating and splitting data.
      package: mluno.regressors
      contents:
        - KNNRegressor
        - LinearRegressor


    - title: Conformal Prediction
      desc: Class for conformal prediction.
      package: mluno.conformal
      contents:
        - ConformalPredictor

    - title: Metrics
      desc: Functions for calculating regression metrics.
      package: mluno.metrics
      contents:
        - rmse
        - mae
        - coverage
        - sharpness

    - title: Plotting
      desc: Function for plotting data and predictions.
      package: mluno.plot
      contents:
        - plot_predictions



